version: '3'
services:
  cdk-validium-prover:
    image: hl/zkevm-prover:v3.0.2
    container_name: cdk-validium-prover
    ports:
      - 50051:50051 # Prover
      - 50052:50052 # Mock prover
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config.json:/usr/src/app/config.json
      - ../prover_src/zkevm-prover/src:/usr/src/app/src
      - ./config:/usr/src/app/config
    command: >
      -c /usr/src/app/config.json
